branches:
  only:
    - master

sudo: required

services:
  - docker

language: python
python:
  - "2.7"

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.14.0

before_install:
  # Install Docker Engine
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

  # Install Docker Compose
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose --version

  # Install other tools
  - pip install coveralls

  # Disable postgres so our container can use Port 5432
  - sudo service postgresql stop

before_script:
  - docker-compose up --build -d

script:
  - docker exec -it djangoosgeoimporter_django_1 mkdir -p -m 777 /app/importer-test-files
  - docker exec -it djangoosgeoimporter_django_1 aws --no-sign-request s3 sync s3://mapstory-data/importer-test-files/ /app/importer-test-files
  - docker exec -it djangoosgeoimporter_django_1 python manage.py test osgeo_importer

after_script:
  - docker-compose down