sudo: required

dist: trusty

language: python

cache:
  directories:
    - gs
    - $HOME/.cache/pip
    - importer-test-files

addons:
  postgresql: "9.3"

services:
 - postgresql

matrix:
  include:
    - python: "2.7"
      env: GS_VERSION=2.7.x GDAL_DATA="/usr/local/lib/gdal/share/gdal/"
    - python: "2.7"
      env: GS_VERSION=2.8.x GDAL_DATA="/usr/local/lib/gdal/share/gdal/"
    - python: "2.7"
      env: GS_VERSION=master GDAL_DATA="/usr/local/lib/gdal/share/gdal/"


virtualenv:
  system_site_packages: true

before_install:
  - chmod +x ./scripts/install.sh
  - chmod +x ./scripts/before_script.sh
  - chmod +x ./scripts/run_tests.sh

install:
  - ./scripts/install.sh
  - pip install coveralls

before_script:
  - sudo scripts/before_script.sh

script:
  - flake8 osgeo_importer
  - ./scripts/run_tests.sh

after_success:
  - coveralls

notifications:
  slack:
    secure: kEr/kA3yDp2dVKAs33veSzUG7QNppwD5E/rCisJwA0hasI/NkW95lCfS9/dqmvPoNiUoYxZwySPJVNVP9u2jAVMhqYe/WjPjm1aGqB3ouSzr/gmm9rfCFTMeR+iDIJgApu0jvEqlq9X4RIO/cOeGsgTinAL+auvkmulacxf2xcyjEXSmre7jSSzr+JLtwpkF67MOl5f9S522L81vVX6KGuYhwYxQFJMFLBtu1WHFzTH+BOssnMpctVYbZvx+zHr79zS/wn2yareUl7yCR2E6PQrGRzZsR1ljg4YTc7tDmSE1cW5ojORJhK1AyieUYRJEIfhIqJ3dp7EK5wrk97oKl6tsoGsNJSpvCnp12+MCW82ioA92K1cuUZi4BBEos538z0eaVqqxFZBdNF5MqvhGg8bAtoE2wnSFrSpTmUMvID5WzNq3U2H+PBOtD67qhTeINEKic6C7tHmNMQTAtz4gZvFPK+3fDktLVIV5dUy6oPbB5zqcEnuIxmLJNl8U3KoiAZo+hwB7QBF6xi2V7yIEvsGHZGNT4ABc+sSgaupbrlePgsKzfQIk6kk97ppbDrSazIKNvf0kJQm0LZzwbkUZVmnfVtkgoF6EeygCxVykCDhsKUJpRZeJB5F/YOXVuXIC/WoFPLN0pRq30oTfoOuEbi1Ik1llvlBueYGBOhiLsuM=
  email:
    on_success: never
    on_failure: never
