version: '2'
services:
  postgres:
    image: mdillon/postgis:9.3
    environment:
     - POSTGRES_USER=osgeo
     - POSTGRES_PASSWORD=osgeo
     - POSTGRES_DB=osgeo
    ports:
     - "5432:5432"
    expose:
     - "5432"
  geoserver:
    build: "geoserver/"
    image: "geoserver-host-postgres:2.9.2"
    ports:
     - "8080:8080"
    links:
     - postgres
